.github/workflows/tox.yml, .yamllint, README.md, docs/contribute/index.md, docs/index.md, mkdocs.yml
Add information about where the documentation is hosted, and how one can contribute to it.
Also, add a README for those who just stumble upon this repo, and include a GitHub Actions workflow that runs the `tox` tests, so we can enable branch protection.
=> Add contribution guide, README, and CI

.github/workflows/tox.yml
When building artifact, by default the name is always build-version.
This is a problem if you're working on multiple PRs for which
you download the artifact: It's now harder to know who is who.
This fixes it by adding the SHA of the virtual merge commit into
the filename of the artifact.
Closes: #6
=> Add merge SHA into build artifact

.github/workflows/tox.yml, mkdocs.yml, tox.ini
Add mkdocs-pdf-export-plugin, which (if Mkdocs is running with the `DOCS_ENABLE_PDF_EXPORT` environment variable set to `1`) renders PDF versions of all pages, and adds a download button right next to the edit button on every page.
=> feat: enable PDF output

docs/How-To_Guides/Object_storage/s3-credentials.md, docs/How-To_Guides/Object_storage/sse-c.md, docs/How-To_Guides/OpenStack/Barbican/generic-secret.md, docs/How-To_Guides/OpenStack/Barbican/index.md, docs/How-To_Guides/OpenStack/Barbican/share-secret.md, docs/How-To_Guides/OpenStack/Cinder/encrypted-volumes.md, docs/How-To_Guides/OpenStack/Octavia/tls-lb.md
Expand the how-to guides section with information on
* How to use Barbican for generic secret storage
* How to share and unshare Barbican secrets
* How to use Barbican for encrypted volumes
* How to use Barbican for HTTPS termination in Octavia
* How to use Barbican for SSE-C against Ceph-backed S3
=> feat: Add how-to guides for Barbican

.github/workflows/tox.yml, docs/How-To_Guides/Object_storage/s3-credentials.md, docs/How-To_Guides/OpenStack/Barbican/generic-secret.md, docs/How-To_Guides/OpenStack/Barbican/share-secret.md, docs/How-To_Guides/OpenStack/Cinder/encrypted-volumes.md, docs/Tutorials/index.md, docs/You_Can_Help!/index.md, docs/index.md, mkdocs.yml, pandoc/README.md, scripts/from-markdown.sh, tox.ini
Add a facility to, with relative ease, create OpenDocument Text and Word documents from the original Markdown. To use, run
```
tox -e to-odt -- -o output.odt input1.md input2.md input3.md
```
or
```
tox -e to-docx -- -o output.docx input1.md input2.md input3.md
```
To achieve this, a simple script concatenates the input files, processes them against `mkdocs.yml` using the Jinja2 CLI, and feeds the result to `pandoc` with appropriate command-line options.
For branding, `reference.docx` and `reference.odt` files can be placed into the `pandoc` subdirectory.
Also, add `bashate` testing for the script itself.
=> feat: Add facility to convert documents with pandoc

tox.ini
It's usually helpful to be able to set a non-standard `-a` option to `mkdocs serve`, in order to listen on a different port if port 8000 is
already in use. Thus, pass positional arguments into the `serve` testenv.
=> build: Pass positional arguments into "tox -e serve"

mkdocs.yml, theme/assets/stylesheets/cleura-palette.css
Being able to switch between light and dark mode is not a gimmick; it's an accessibility issue: people living with migraines often find it extremely uncomfortable and/or painful to look at large bright white areas on their screen.
Thus, add a light/dark mode switch, and also detect the global system or browser setting to provide a reasonable default.
=> feat: Enable light and dark mode, and detect system setting

docs/CNAME
GitHub Pages custom domains are meant to be enabled in one of two ways: via the repository settings (Settings → Code and automation → Pages → Custom domain), or via a `CNAME` file in the root of the repository's `gh-pages` branch.
It appears that the former option is not working, in the sense that it gets cleared on every deployment run. This, then, results in the site effectively disappearing (i.e. producing HTTP 404s).
Thus, opt for the latter option and do use the `CNAME` file.
=> build: Add CNAME file

docs/howto/openstack/neutron/.pages, docs/howto/openstack/neutron/multiple-public-ips.md
In previous version of docs [1] we stated that it's impossible to have
multiple Floating IPs per server without need to have multiple ports
assigned which is simply not true.
We describe how it's possible to achieve in a couple of simple commands.
[1] https://kb.citynetwork.eu/kb/how-to-articles/openstack/add-multiple-ips-on-a-server
=> Document how to have several Floating IP for a Port

docs/howto/openstack/octavia/tls-lb.md
* Fix a couple of small errors in the Octavia HTTPS termination how-to.
* Add info on how to update a TLS listener with a new secret.
=> Octavia HTTPS termination update

docs/reference/features/compliant.md
sto1hs and sto2hs have no IPv6 support yet
this work is not prioritized as of today
=> fix: IPv6 in compliant

docs/reference/features/public.md
Since the closed beta for Gardener in Public Cloud is now underway, mention it as a feature that is in deployment, but not yet supported.
Simultaneously, also add Magnum to the feature matrix, which has been officially supported since 2018.
Reference:
https://cleura.com/press-releases/city-network-launches-container-service-in-city-cloud-with-kubernetes-in-focus/
=> feat: Add Kubernetes cluster management to feature support matrix

mkdocs.yml
SmartyPants adds a few clever typography features to Markdown, such as intelligently turning "straight quotes" into “curly quotes”, three dashes (---) into one em dash (—), and three dots (...) into ellipsis (…).
Reference:
https://python-markdown.github.io/extensions/smarty/
=> feat: Enable the Python-Markdown SmartyPants extension

docs/reference/versions/compliant.md
As of October 2022, all our Compliant Cloud deployments run Ceph Pacific and OpenStack Xena. Update the version matrix accordingly.
=> fix: Update version references in Compliant Cloud

.github/workflows/build.yml
By default, `gitlint` only lints the most recent commit message. In a PR, when invoked from GitHub Actions, that is always a merge commit, which `gitlint` always succeeds on.
Thus, use the `ref` argument on the GitHub Actions `checkout` action to instead fetch the corresponding top non-merge commit.
=> build: Run gitlint against a PR's head commit, not the merge commit

docs/reference/versions/public.md
Since May 2022, all our Public Cloud deployments run Ceph Pacific. Update the version matrix accordingly.
=> fix: Update Ceph version references in Public Cloud

.gitignore
There are specific MacOS-generated files we always want to ignore.
=> chore: Add .gitignore file

docs/contrib/index.md, docs/contrib/modifications.md, docs/contrib/quality.md
In order to make contributions to the documentation more accessible to
occasional or casual contributors, spell out how to fork and clone the
documentation repo in the contribution guide, using two approaches:
1. Using the GitHub web interface plus the `git` CLI,
2. Combining the `git` and `gh` CLIs.
This then makes the single-page configuration guide a little unwieldy,
so split it into 3 pages.
=> feat/refactor: Expand Git information in contribution guide, split into 3 pages

docs/contrib/modifications.md
In the review for PR #39, we missed a missing word ("content") in a
section heading. Add it.
=> fix: Add missing word in contribution guide heading

.github/workflows/build.yml, .mailmap
Having added a few more contributors as of late, all of whom have both cleura.com and citynetwork.eu addresses, update the .mailmap file so as to keep the mkdocs-git-authors plugin happy.
Also, fix the GitHub Actions workflow definition to more reliably install the `weasyprint` package, by running `apt-get update` before `apt-get install`.
=> chore: Update .mailmap

docs/contrib/modifications.md, mkdocs.yml
The htmlproofer plugin increases documentation build times nearly tenfold. This may be undesirable when making quick changes while running `tox -e serve`. Thus, introduce an environment variable, `DOCS_ENABLE_HTMLPROOFER`, and disable the plugin if it is set to `false`.[^1]
Since this means that `mkdocs.yml` no longer contains `true` or `false` for a boolean variable, disable the yamllint `truthy` check for that line.[^2]
Also, update the contribution guide to that effect.
[^1]: https://www.mkdocs.org/user-guide/configuration/#environment-variables
[^2]: https://yamllint.readthedocs.io/en/stable/disable_with_comments.html#disabling-checks-for-a-specific-line
=> build: Use environment variable for toggling htmlproofer

docs/howto/getting-started/enable-openstack-cli.md
Setting `CLIFF_FIT_WIDTH` is a helpful tweak for the `openstack` CLI, which keeps it from generating excessively long lines in tabular output. Mention it in the appropriate Getting Started section.
=> feat: Mention CLIFF_FIT_WIDTH in Getting Started page for CLI

docs/reference/features/compliant.md, docs/reference/features/public.md
Update the feature support matrix in the reference section with links
to Barbican-related how-to guides (for volume encryption, S3 SSE-C,
and HTTPS termination in Octavia).
=> feat: Update feature support matrix with links to encryption howtos

.mailmap, mkdocs.yml, tox.ini
Since version 0.6.5, the git-authors plugin has the option of only showing the author's name(s), rather than rendering them as a
`mailto:` link. Since we want to list contributors but don't want to open them to spam, set the `show_email_address` option to `false`.
Also, fix up the `.mailmap` file so author identities are properly merged, and every person shows up as an author only once for every page (in other words, we avoid listings like "John Doe, Emily Example, John Doe" under a page).
=> build: Don't show email addresses for authors

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/functional_bug.md, .github/ISSUE_TEMPLATE/textual_bug.md, docs/index.md
Add a couple of patches to better explain what "beta" means for the site, and to enable people to file bugs if they see them:
- feat: Expand Beta disclaimer, add call to action for documentation bugs
- docs: Add GitHub issue templates
=> Add beta disclaimer and issue templates

.github/ISSUE_TEMPLATE/functional_bug.md, .github/ISSUE_TEMPLATE/textual_bug.md
Small follow-up to #49:
When creating an issue using the GitHub issue template, and entering preview mode, the issues look odd when they use pre-wrapped lines. To make the experience smoother for issue reporters, unwrap the templates so they use long lines instead.
=> fix: Unwrap long lines in issue templates

docs/contrib/modifications.md
Add a note recommending 1080p resolution for GUI screen shots, and a 100-character width limit for CLI screen dumps.
=> docs: Update contrib guide with suggestions for screen shots/dumps

docs/reference/versions/index.md
In the Reference section, the version overview was still mentioning
OpenStack Victoria and Ceph Nautilus. Since these versions are no
longer in use anywhere in Cleura Cloud, remove those mentions.
=> fix: Remove residual mentions of OpenStack Victoria and Ceph Nautilus

docs/howto/index.md
Apparently due to a botched edit at some point, the overview page for
our how-to guides used verbs in the gerund ("-ing form") when they
should be using the indicative. Fix those glitches.
=> fix: Correct grammar in how-to overview

.github/workflows/build.yml, .github/workflows/deploy.yml
We are currently getting false positives from the htmlproofer plugin
when it runs from GitHub Actions workflows, in that it reports links
as dead that are evidently alive. This is probably due to bandwidth
throttling or DDOS protection misfiring on the target sites.
This patch should be reverted as soon as the issues subside.
=> chore: Temporarily disable htmlproofer in GitHub Actions workflows

docs/index.md, mkdocs.yml, theme/partials/integrations/analytics/plausible.html
Plausible is a cookieless, privacy-preserving, GDPR compliant site
analytics solution that is already in use on https://cleura.com.
Using a theme override, include the Plausible analytics snippet on
every page. Mention Plausible on the start page.
References:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#custom-site-analytics
https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
https://plausible.io/data-policy#how-we-count-unique-users-without-cookies
=> feat: Add Plausible analytics

docs/howto/openstack/nova/.pages, docs/howto/openstack/nova/config-drive.md
- refactor: Reorder pages in OpenStack Nova how-to section
- refactor: In config-drive howto, say "server" rather than "instance"
=> Reorder pages in Nova howto section, rephrase config-drive howto

docs/concepts/index.md, docs/contrib/modifications.md, docs/howto/getting-started/create-account.md, docs/howto/getting-started/enable-openstack-cli.md, docs/howto/index.md, docs/howto/kubernetes/gardener/create-shoot-cluster.md, docs/howto/kubernetes/index.md, docs/howto/object-storage/s3/credentials.md, docs/howto/object-storage/s3/expiry.md, docs/howto/object-storage/s3/sse-c.md, docs/howto/object-storage/s3/versioning.md, docs/howto/openstack/barbican/generic-secret.md, docs/howto/openstack/barbican/index.md, docs/howto/openstack/barbican/share-secret.md, docs/howto/openstack/cinder/encrypted-volumes.md, docs/howto/openstack/neutron/multiple-public-ips.md, docs/howto/openstack/neutron/new-network.md, docs/howto/openstack/nova/config-drive.md, docs/howto/openstack/nova/new-server.md, docs/howto/openstack/octavia/tls-lb.md, docs/index.md, docs/reference/features/index.md, docs/reference/flavors/index.md, docs/reference/index.md, docs/reference/versions/index.md, docs/tutorials/index.md, mkdocs.yml
Prior to this change, we referred to macros defined in the `extra` dictionary of `mkdocs.yml` either with the `extra.` or even the
`config.extra.` prefix.
As [the mkdocs-macros-plugin documentation](https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages/#configuration-variables
) explains, this is actually not necessary: any variables defined in `extra` can be referred to without such a prefix, and it is only when we want to access other variables in `config` (such as `config.repo_url`) that we need to fully qualify them.
Since the documentation sources become much more concise that way, use the abbreviated (unqualified) syntax.
Note: referring to the variables in this manner obviously means that in the `extra` dictionary we cannot have any top-level keys named `config`, `page`, …
=> chore: Drop "extra." and "config.extra." prefixes from macros

.github/workflows/build.yml, .github/workflows/deploy.yml
We want to use the htmlproofer plugin for deployments, and only
disabled it in GitHub Actions because we were getting false positives
(presumably due to bandwidth throttling or DDOS protection on the
target sites).
This reverts commit 9454deec5081e74531fa37adbc7a23c39758c551.
=> chore: Re-enable htmlproofer in GitHub Actions workflows

docs/howto/getting-started/create-account.md, docs/howto/openstack/neutron/.pages, docs/howto/openstack/neutron/new-network.md, docs/howto/openstack/nova/new-server.md
* Remove "in Cleura Cloud" from section headings. It doesn’t make much
sense to keep it, because it’s obvious and redundant.
* Reorder pages in OpenStack Neutron how-to section, so that we don’t
talk about networking specifics before explaining how to create a
network.
=> Small navigation updates

docs/contrib/modifications.md
* Discourage contributors from conjuring up new top-level or
second-level sections.
* Mention the "assets" directory for screen shots.
=> docs: Updates to Contribution Guide

docs/reference/features/public.md
In the Sto2 region, a feature that is currently rolling out is
Dedicated CPU, not Virtual GPU. Fix the reference information
accordingly.
=> fix: Correct information on Dedicated CPU and Virtual GPU availability

docs/howto/kubernetes/gardener/create-shoot-cluster.md, docs/howto/kubernetes/gardener/index.md, docs/howto/kubernetes/index.md, docs/howto/kubernetes/magnum/index.md
* Add `index.md` files in the `howto/kubernetes/magnum` and `howto/kubernetes/gardener` directories.
* Move generic information about Gardener and Magnum into those files.
* Clarify that Gardener is in closed beta, and add instructions on how to enroll in it.
=> refactor: Slightly reorganize Kubernetes how-tos

docs/howto/getting-started/create-account.md
CDPA and GTC documents were migrated from citycontrolpanel.com to object storage. The "Create Account" page had to be updated with new links.
=> Update links to CDPA and GTC documents

.github/workflows/build.yml, .github/workflows/deploy.yml
GitHub advises against the use of actions using Node.js 12. This is true for the v2 releases of the `checkout` and `setup-python`
actions. Thus, bump those actions to their latest versions (v3 and v4, respectively).
While we're at it, bump the `upload-artifact` action to v3 as well.
Reference:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> build: Bump version tags for GitHub actions

docs/contrib/index.md, docs/contrib/modifications.md, docs/howto/getting-started/enable-openstack-cli.md, docs/howto/index.md, docs/howto/kubernetes/gardener/index.md, docs/howto/kubernetes/index.md, docs/howto/object-storage/s3/index.md, docs/howto/object-storage/swift/index.md, docs/howto/object-storage/swift/public-container.md, docs/howto/openstack/barbican/generic-secret.md, docs/howto/openstack/magnum/new-k8s-cluster.md, docs/howto/openstack/neutron/create-security-groups.md, docs/howto/openstack/neutron/new-network.md, docs/howto/openstack/neutron/vpnaas.md, docs/howto/openstack/nova/config-drive.md, docs/howto/openstack/nova/new-server.md, docs/howto/openstack/nova/resize-server.md, docs/index.md, docs/reference/features/index.md, docs/reference/flavors/index.md, docs/reference/versions/index.md, mkdocs.yml
We did a poor job at defining the `company` and `brand` extra variables early on. `company` should really refer to the company name (in our case, "Cleura"), and `brand` should refer to the cloud product (in our case, "Cleura Cloud").
Update the variables accordingly, and fix the references.
=> refactor: Set "company" to "Cleura", "brand" to "Cleura Cloud"

docs/howto/object-storage/s3/expiry.md
Previously, we only explained how to enable object expiry on an
S3 bucket. Extend the how-to guide to also cover removing the
object expiry lifecycle policy.
=> feat: Explain how to disable object expiry in the S3 how-to

docs/howto/openstack/nova/.pages, docs/howto/openstack/nova/server-group.md
This is a guide explaining server groups and how to use them.
This is a rewrite of the old guide from https://kb.citynetwork.eu/kb/how-to-articles/openstack/use-of-server-groups-in-city-cloud
=> feat: Add HowTo using server groups

docs/howto/getting-started/accessing-cc-rest-api.md, mkdocs.yml
Just to ensure that we are consistent across pages, and to facilitate
any future changes to the Cleura Cloud REST API name or the domain
where we host it, introduce macro variables for both of them.
=> refactor: Introduce macros for the REST API and its domain

.github/ISSUE_TEMPLATE/gap.yml
Up to this point we have only allowed bug reports, because the site was known to be very incomplete and we had a long list of things to add before we could even consider it useful.
Now, we are getting much closer to that stage, and once we are satisfied that we can take on documentation requests, we should be ready to take them on.
Since this is GitHub specific, and the issue template can only be meaningfully tested if this change lands in main, we merge it now, test it, and then back it out again to be brought back once we drop the "beta" moniker for the site.
This uses a YAML issue template, rather than the Markdown ones we have been using for bug reports thus far.
Reference:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-i …
=> docs: Add an issue template for missing or incomplete documentation

.github/ISSUE_TEMPLATE/gap.yml
Fix the following issues by which the `gap.yml` issue template was invalid as per the applicable schema:
* Remove the `title`, `assignees`, `labels` keys (which cannot be blank if set, and it does not make sense to preseed a value for them).
* Remove the `about` key, replace it with `description`.
* Fix typo in `validations` (was `validation`).
References:
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms 
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
=> fix: Correct YAML syntax for issue template

.github/workflows/build.yml
Since we are not using a `[gh-actions]` section in `tox.ini`, there is really no need to keep installing `tox-gh-actions`. Drop it.
In addition, rather that enumerating all the testenvs we want to run from our GitHub Actions workflow, just invoke `tox` twice: first check with only `gitlint`, then run the default testenvs specified in `tox.ini`'s `envlist`.
=> build: Drop tox-gh-actions, simplify tox invocation from GitHub Actions

.github/ISSUE_TEMPLATE/gap.yml
It's a bit silly to use a multi-line textarea for a URL, so just
change it to a one-line input box.
=> fix: Change URL textarea to input in issue template

docs/howto/getting-started/accessing-cc-rest-api.md
In the getting started guide for using the REST API, explain that accounts with only Webauthn 2FA are unsuitable for REST API use, and that instead users must configure an account with SMS as a second factor.
Also, specify that users should always specify the `twofa_method` parameter and set it to `"sms"`: if they have only SMS configured as a second factor, it won't hurt to use that parameter. If they have SMS _and_ Webauthn, they must set it (even though Webauthn doesn't work for getting a token).
=> fix: Explain that the REST API only supports SMS 2FA

docs/contrib/modifications.md, mkdocs.yml
Our contribution guide mentions an edit button on every page. However, as of mkdocs-material 9, this edit button is no longer on by default if `repo_url` is set, but it is toggled by a feature flag. It also uses a different icon.
Enable the feature flag, and also update the contribution guide to refer to the updated icon. In doing so, use a bit of Jinja trickery with mkdocs-macros so that the in-text edit icon auto-updates with the one in the configuration (in case we ever change it).
Reference:
https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
=> fix: Restore edit button

docs/reference/api/openstack/.pages
Fix the navigation so that it says "OpenStack API" in the API reference section, akin to "Cleura Cloud REST API".
(This file was accidentally omitted from #108.)
=> fix: Add missing .pages file in OpenStack API reference section

docs/howto/object-storage/s3/.pages, docs/howto/object-storage/s3/public-bucket.md
Explain how to use S3 bucket policies to make all objects in a bucket publicly accessible via a browser or `curl`, and optionally how to enable bucket listing.
=> feat: Add how-to guide for creating a publicly readable S3 bucket

.githooks/pre-commit, .githooks/pre-push, .github/workflows/build.yml, .github/workflows/deploy.yml, tox.ini
PDF exports of the documentation pages are currently broken in two ways:
* Content tabs no longer convert to subsections that are shown one after the other, like they used to.
* Fenced code blocks render in a proportional, rather than a monospace font.
This renders the PDF output essentially useless, so until we can fix it, just disable it.
Also, set/unset the dead link checker in Git hooks. It's usually tedious and time-consuming to run the dead link checker on every commit, particularly if one is working on a local topic branch that gets frequent commits. So, update the `pre-commit` hook script to disable it (unless it has been specifically enabled in the environment already). However, enable it unconditionally in the `pre-push` hook so that we don't create broken pull requests.
In …
=> build: Toggle link checker in Git hooks, disable PDF output

docs/howto/object-storage/s3/.pages, docs/howto/object-storage/s3/presign.md
Explain how to create pre-signed URLs. Also explain how the `Content-Disposition` header affects objects downloaded from pre-signed URLs.
=> feat: Add how-to guide for pre-signed URLs

docs/howto/object-storage/s3/public-bucket.md, docs/howto/object-storage/swift/public-container.md
It perhaps isn't immediately obvious that our object storage buckets
and objects are one and the same when accessed via alternative paths
to the S3 and Swift APIs, and that as a result once an object has been
made public via one API, it's also public via the other.
Thus, add cross-references between the corresponding S3 and Swift
how-to guides explaining this.
=> feat: Explain that Swift and S3 public URLs are interchangeable

docs/howto/openstack/cinder/sync-volumes.md
In the how-to guide on synchronizing volumes with minimal downtime, explain that the process does not apply for boot volumes (and suggest to retype those volumes offline, instead).
=> fix: Explain that the volume sync doesn't apply to boot volumes

docs/reference/features/compliant.md, docs/reference/features/public.md, docs/reference/flavors/index.md
The documentation was previously overly optimistic about the "coming soon" state of this feature. Remove it from the feature matrix and flavor reference, so as not to confuse users.
=> fix: Stop mentioning Dedicated CPU

docs/howto/openstack/octavia/.pages, docs/howto/openstack/octavia/lbaas-l7pol.md
We show how to add automatic HTTP to HTTPS redirection to an Octavia HTTPS-terminated load balancer.
=> feat: Add HOWTO: Auto HTTP-to-HTTPS for Octavia LB

docs/howto/getting-started/create-account.md, mkdocs.yml
Since it might come in handy using references to legal documents
in multiple spots in the documentation, define macros for them.
=> refactor: Replace direct links to legal documents with macros

docs/background/.pages, docs/background/project-deletion.md
Explain why deleting a project (tenant) is not as simple as it sounds, and inform that this kind of functionality is not available to Cleura Cloud customers. Disabling a project, though, is allowed, and interested customers can do so via the Cleura Cloud REST API.
=> feat: Add BG info: Advise against wiping out PRJs

docs/howto/kubernetes/gardener/create-shoot-cluster.md, docs/howto/kubernetes/gardener/index.md, docs/howto/kubernetes/index.md, docs/reference/features/public.md, mkdocs.yml
Since the service will launch with some name that will most probably not be "Gardener", replace the hard-coded mentions thereof with a macro reference.
=> refactor: Add macro placeholder for "Gardener"

.github/workflows/deploy.yml
The link checker (which we can enable and disable by toggling the `DOCS_ENABLE_HTMLPROOFER` variable) is not always reliable: for example, if one of the links we check uses some form of bandwidth throttling or DDOS protection, it might temporarily refuse access from the GitHub CI hosts.
In the build pipeline that isn't a problem: we can just re-run the failed job.
However, once we have merged a change and we've determined (during the pre-merge checks) that all links are alive, it does not make much sense to re-check on deploy, and possibly hold up the deployment because of a temporarily unavailable link.
Thus, just disable the link checker in the deploy stage.
=> build: Disable link checking on deploy

.github/workflows/build.yml, .github/workflows/deploy.yml, mkdocs.yml, tox.ini
We've had PDF export disabled in our builds for a while now (since #111), and nobody appears to be missing it.
Thus, remove the PDF export plugin, which also means we no longer need to install the `weasyprint` package in the build environment (which, in turn, speeds up the CI build checks).
=> build: Remove PDF export plugin

docs/reference/versions/public.md
After upgrades performed in several regions new versions of Ceph were introduced.
=> Update Ceph service versions in Fra1, Dx1 and Tk1

docs/reference/versions/index.md
We forgot to mention Ceph Quincy in one other place, when we merged 33536d76631aa0225142c7ed5261a483d8230d85. Fix that reference.
=> fix: Mention Ceph Quincy in version overview

docs/reference/features/compliant.md
Fix the broken link to the S3 SSE-C howto from the Compliant Cloud feature reference page.
=> fix: Correct link to SSE-C from Compliant Cloud features reference

docs/howto/object-storage/s3/.pages, docs/howto/object-storage/s3/credentials.md, docs/howto/object-storage/s3/sse-c.md
* Besides `rclone`, also explain SSE-C for the `aws` and `mc` CLIs (and mention that you can't use SSE-C with `s3cmd`).
* Move information about setting up `rclone` into a content tab in the "Working with S3-compatible credentials" how-to guide.
* Change the page title (the "C" in "SSE-C" stands for "customer", not for "client").
* Fix the invalid bucket name in the example (bucket names cannot contain `:`).
* Shorten the page's navigation entry.
* Add a description to the YAML front matter.
=> feat: Rewrite S3 SSE-C examples, add support for additional CLIs

docs/howto/openstack/nova/new-server.md
In our "new server" how-to guide, we previously omitted the ability to connect to the new instance via SSH, using the `openstack server ssh` command.
Fix that omission.
=> fix: Mention "openstack server ssh"

docs/reference/limitations/openstack.md
Mention that although we do use BGP dynamic routing internally (which explains why the API endpoints exist), we do not expose that functionality to non-admin users.
=> feat: Explain dynamic routing limitations

docs/howto/openstack/magnum/new-k8s-cluster.md
CCMP-launched Magnum clusters currently do *not* allow OpenStack CLI users to successfully download cluster credentials.
This, sadly, renders CCMP-launched Magnum clusters functionally unusable for use with Kubernetes: one can spin up a cluster, but one has no way of pointing `kubectl` at it and actually do anything with the cluster.
Thus, until a kubeconfig download button is implemented in CCMP, remove the CCMP-related bits from the Magnum cluster spin-up howto, and declare that functionality CLI-only.
This PR also includes a number of smaller changes and chores, including a reformat of the guide.
But the important changes are in 2e55ed1009f80465dee08c2fd4160aae8c4f26d8 — I have put them in a separate commit so they should be straightforward to revert, once the missing functionality has …
=> fix: Drop CCMP references from Magnum cluster how-to guide

docs/reference/api/openstack/index.md
The OpenStack API reference had two internal links to how-to guides that were dead because they used the wrong relative URL. Fix those.
=> fix: Correct internal links in OpenStack API reference

docs/background/.pages
Rather than using the full title of the background explanation pages in the navigation menu, shorten them via the `.pages` file.
=> chore: Shorten navigation entries for background pages

docs/reference/limitations/object-storage.md
radosgw ignores the `.rlistings` ACL element on Swift containers, and always allows listing a container's contents if the container's objects are readable.
Mention this in the limitations reference section.
=> fix: Mention missing support for .rlistings ACL element in Swift API

docs/reference/features/public.md, docs/reference/versions/public.md
We now run Ceph Quincy in Sto2 and Swift/S3 are available in Tky1.
=> fix: Update Ceph service version for Sto2 and Tky1

docs/howto/object-storage/s3/object-lock.md, docs/reference/features/compliant.md, docs/reference/features/public.md
Explain that S3 object lock is not available in all regions, and add it to the feature support matrix.
=> feat: Document S3 object lock availability on a per-region basis

docs/howto/kubernetes/gardener/.pages, docs/howto/kubernetes/gardener/create-shoot-cluster.md, docs/howto/kubernetes/gardener/kubectl.md
* Split the Gardener "create shoot cluster" how-to into two guides, by factoring out the information on getting a kubeconfig into a separate page.
* Explain how Gardener manages the DNS entry for the API server's address.
Since this makes a cross-reference to hibernation, this PR can land only after #151 does.
=> Add information about dynamically-managed DNS records in Gardener clusters

docs/howto/kubernetes/gardener/.pages
The `.pages` file introduced in c3799e590f10323d50150819d8c76780f45c4187 accidentally hid the just-introduced Gardener hibernation howto.
Fix it to return the howto to the navigation menu.
=> fix: Re-instate Gardener hibernation how-to navigation entry

docs/background/.pages, docs/background/kubernetes/gardener/autoscaling.md, docs/howto/kubernetes/gardener/.pages
Explain how autoscaling works, and how it may be impacted by running cluster workloads.
#151 and #153 must land before this.
=> feat: Add background information on Gardener autoscaling

docs/background/.pages, docs/background/kubernetes/gardener/hibernation.md
We explain how hibernation in Gardener-based clusters actually works, how the pricing structure changes for hibernated clusters and, finally, what may go wrong while attempting to wake an already hibernated cluster.
=> feat: Add BG info on hibernating/waking clusters

docs/background/kubernetes/index.md, docs/howto/kubernetes/index.md, mkdocs.yml
Add a brief tabular comparison between Magnum and Gardener.
Since this requires some additional information that isn't suitable to be added into the table directly, enable the `footnotes` Markdown extension and put it in footnotes.
Also, add a back-link from the Kubernetes subsection in the howto guides section.
=> feat: Add comparison between Magnum and Gardener

docs/howto/kubernetes/gardener/kubectl.md, docs/howto/openstack/magnum/.pages, docs/howto/openstack/magnum/kubectl.md, docs/howto/openstack/magnum/new-k8s-cluster.md
* Create a new page, `kubectl.md`, in the OpenStack Magnum how-to guides section (similar to what we already have for Gardener).
* Explain that one must use CCMP to download the kubeconfig of a CCMP-managed Magnum cluster, and the CLI for a CLI-managed one.
* Instead of specifically discussing how to install kubectl on Debian/Ubuntu and MacOS, point to the upstream documentation.
=> refactor: Split kubeconfig information for Magnum into a separate page

docs/howto/getting-started/create-account.md
The sentence referring to the ToS and CDPA was missing punctuation. Fix the missing full-stop, and also inject a newline to break the paragraph.
=> fix: Inject full-stop and newline in account creation how-to guide

docs/background/kubernetes/gardener/autoupgrades.md
When we create a Kubernetes cluster with Gardener, there is a maintenance window during which automatic upgrades take place. This feature is specific to Cleura Cloud, so it makes sense to clarify that.
=> fix: Be more specific re. autoupgrades in Gardener

docs/reference/.pages, docs/reference/index.md, docs/reference/legal/index.md
Create a page containing links to our legal documents.
Also, explain the relationship between the legacy GT&C and their replacement, the ToS.
=> feat: Add a Legal page to the Reference section

docs/howto/account-billing/change-billing-data.md
Encase legal_docs.transfer_form.name in double curly brackets, so the variable value is used in the provided URL (legal_docs.transfer_form.url).
While we're at it, apply the one-sentence-per-line policy and introduce some minor changes to syntax and prose.
=> fix: Make sure variable name is properly referenced

.github/workflows/build.yml, mkdocs.yml
Our object storage services now support access via the standard HTTPS port, 443. This transition has not yet been completed in all regions, so we cannot update the S3 and Swift API how-to guides yet, but it has been completed in the Kna1 region so we can update the references to the publicly accessible legal documents.
Thus, drop the `:8080` port suffix from those macro definitions.
=> fix: Drop :8080 port suffix from public S3 links

docs/reference/limitations/openstack.md
Explain that we only support Linux guests for nested virtualizations, and that they must run reasonably recent kernel and KVM versions and pass in the pcid CPU feature flag.
=> feat: Add limitations for nested virtualization

docs/howto/getting-started/create-account.md
Rather than sending customers to the CCMP start page and then walking them to the account creation page, we can instead instruct them do drop directly on the registration page.
This saves one step, and removes the need for one screenshot.
=> fix: Use shortcut for account registration

docs/reference/versions/index.md, docs/reference/versions/public.md
Ceph Quincy is now deployed and available in all public cloud regions, including Kna1.
=> fix: Update Ceph version name in Kna1 region

docs/reference/versions/index.md
Although all Public cloud regions now run Ceph Quincy, there is still Ceph Pacific in Compliant cloud. So re-instate the mention of Pacific in the version overview.
=> fix: Re-mention Ceph Pacific in version overview

docs/reference/versions/compliant.md
Ceph Quincy is now deployed and available in Sto1HS region, in the compliant cloud.
=> fix: Update Ceph version in Sto1HS region

.github/workflows/build.yml
This reverts commit b87ec4e9620ac6e8549a0d619d34fed1920aad2d.
=> build: Re-enable htmlproofer plugin in GitHub Actions workflow

docs/reference/legal/index.md, mkdocs.yml
The transition period, during which the old GT&C still applied to accounts created before 2023-04-05, ends on 2023-05-05. As of that date, the new ToS applies to all accounts.
Thus, remove the remaining references to the old terms.
=> fix: Remove references to the old General Terms and Conditions

docs/reference/versions/compliant.md, docs/reference/versions/index.md
Ceph Quincy is now deployed and available
in Sto2HS region, in the compliant cloud.
=> fix: Update Ceph version in Sto2HS region

.githooks/pre-push, .github/workflows/check.yml, .github/workflows/deploy.yml, .gitignore, .linkcheckerrc, mkdocs.yml, tox.ini
Our automated checks for dead links haven't been functional, or at least not reliable as far as external links are concerned, for a while now. Since we can't really make them work reliably with the htmlproofer plugin because of https://github.com/manuzhang/mkdocs-htmlproofer-plugin/issues/63, try an alternate approach with linkchecker. 
- build: Drop envdir from testenv
- build: Replace htmlproofer plugin with linkchecker
=> Bring back external link checking

.github/workflows/check.yml
Adding this event trigger is necessary to allow us to invoke the
workflow run manually.
References:
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
=> build: Add workflow_dispatch event trigger to check.yml

.github/workflows/check.yml, .gitignore, .linkcheckerrc, docs/background/disaster-recovery.md, docs/background/object-storage.md, docs/howto/openstack/nova/boot-image-volume.md, docs/reference/api/cc/index.md, tox.ini
The initial test runs with the `check` workflow seem to indicate that several dead links slipped through the `htmlproofer` plugin, meaning it was probably not very useful to begin with.
Also, the `page_build` trigger never seems to trip, even though [I think we were using it correctly](https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/ci-cd/github-actions/triggers.html#trigger-on-a-gh-pages-build), so remove it from the configuration.
=> Final touchups to link checking

docs/background/disaster-recovery.md
This was mixed up in two prior commits, and then missed in review.
This reverts commit ecb633f27b06557cee9162935e4d4c25a8328863.
=> fix: Work around HTTP 500 at ceph.io (again)

scripts/linkcheck.sh
The scheduled production link check had an extra set of single quotes.
It doesn't seem to actually break the link check, but it doesn't hurt
to remove the superfluous quotes.
=> chore: Fix superfluous quotes in production link check

docs/reference/features/public.md
At the moment all infrastructure and bits are ready for
GPU-powered VM signups in kna1 and sto2 regions.
=> feat: Mark vGPU feature as complete for kna1 and sto2

docs/background/kubernetes/index.md, docs/reference/limitations/kubernetes.md
The latest available Gardener-managed Kubernetes version in Cleura Cloud is no longer 1.24, but 1.26. Fix the relevant background and reference pages.
=> fix: Bump latest supported Kubernetes version for Gardener

scripts/linkcheck.sh
Whatever gremlins there are that cause all of our link check facilities to choke on this one specific server we might not ever know.
But we can't keep having our builds break on this.
=> build: Add s3-kna1.citycloud.com to the linkcheck ignore list

docs/howto/openstack/glance/.pages, docs/howto/openstack/glance/examine.md, docs/reference/images/index.md
This is the continuation of #220, created to avoid force-push issues.
=> Expand reference section on image metadata, add image inspection how-to

docs/howto/openstack/glance/examine.md
The missing console prompt messes up syntax highlighting when used with the `console` lexer.
=> fix: Add missing "$" in fenced code block

docs/reference/images/index.md
We have recently switched our image rotation mechanism from
deactivating the image, which makes impossible any futher usage of the
image, to marking them as "comminuty" ones. This allows to use
already rotated image in case of need. Potential usecases are:
* Server rebuild
* New images somehow misbehave
* User will to use exact same image for another VM in the cluster
While usage of community images is inadvisable, we still should
mention their existance.
=> feat: Mention community images in reference

docs/howto/openstack/nova/restore-srv-to-snap.md
Most how-to guides in the openstack/nova section use a heading along the lines of "Doing X to a server", rather than "Doing X to server".
The how-to guide on restoring from a snapshot was the only deviation from this. Inject the indefinite article into the heading, in order to be in line with the other headings.
=> fix: Insert missing article in heading

docs/howto/openstack/nova/new-vgpu-server.md, docs/reference/features/public.md
Given the fact that it is not yet possible to launch a vGPU-enabled server using CCMP, err on the side of caution and mark it as "in deployment, not yet supported" rather than "in production and fully supported".
However, now that we have a how-to guide for launching vGPU enabled servers, link that how-to rather than just the flavor reference. Also, update the how-to explaining that vGPU support is only available in select regions, and add a backlink to the feature support matrix.
=> fix: Revert vGPU support to "in deployment, not yet supported"

docs/reference/features/public.md, docs/reference/flavors/index.md
At the moment we do have publicly available flavors for CPU-intense compute
aggregate in STO2 region. It make sense to describe the feature and add
it's support to the matrix.
=> feat: Add support for CPU-intense flavors

docs/reference/features/public.md, mkdocs.yml
Since MkDocs 1.5, we can add a `validation` map to the configuration file, which we can use to upgrade validation `INFO` messages to the `WARNING` level — and this, in combination with the `--strict` setting in the `build` testenv, can flag such issues as errors. This is what we want, thus, set the values that MkDocs lists as "recommended settings for most sites (maximal strictness)".
Reference:
https://www.mkdocs.org/user-guide/configuration/#validation
=> build: Add validation parameters to mkdocs.yml

.pymarkdown.json, docs/contrib/modifications.md, docs/howto/openstack/nova/server-group.md
Implement a few changes in the Markdown linter:
* Set the maximum line length for non-code-blocks and non-headings to 200 characters.
* Set the maximum line length for headings to 80 characters
* Disable line length checking for code blocks.
The rationale behind this is that it enables us to adopt a Markdown style with one sentence per line. This style has the following benefits:
* It facilitates code reviews, as it ensures that any change to a sentence is also a change to a line, and vice versa.
* It makes long run-on sentences stand out visually while editing, encouraging the author to break them into shorter and more readable sentences.
* It has no bearing on the flow of the rendered text, since the Markdown renderer will only care about line breaks preceded by two spaces (which become …
=> Update linter configuration, facilitate one-sentence-per-line policy

mkdocs.yml
We generally want "Cleura Cloud" to not break across a newline, so update the extra variable to include a non-breaking space.  Also, ensure that "Cleura Cloud Management Panel" and "Cleura Cloud REST API" only break into two halves, as opposed to just randomly.
=> fix: Add non-breaking spaces to brand names

docs/reference/versions/index.md, docs/reference/versions/public.md
* Mention that Public Cloud is transitioning to Antelope (from Xena).
* Explain why we skip both Yoga and Zed, as opposed to just Yoga.
* Update the OpenStack version for Tky1 to Antelope.
=> fix: Update version reference for Antelope

docs/reference/limitations/openstack.md, tox.ini
When launching a Nova server in Cleura Cloud, using one of the images marked as public in Glance, the guest operating system gets VirtIO block (`virtio-blk`) devices to work with. In the guest operating system, these images are named `/dev/vda` for the boot block device, and `/dev/vdb`, `/dev/vdc` etc. for attached volumes. Since VirtIO only enumerates devices up to `/dev/vdz`, this means it can only handle 26 devices in total, and thus a single server can only ever attach 25 volumes concurrently.
Until we have the option of running from public images configured with `virtio-scsi` (which does not have this limitation), state that 25 is the maximum number of volumes that can be concurrently attached to a single server.
=> fix: Mention limit of 25 concurrently attached volumes

.linkcheckerrc, docs/background/kubernetes/gardener/autoscaling.md, docs/background/kubernetes/gardener/garden-linux.md, docs/background/kubernetes/gardener/hibernation.md, docs/background/object-storage.md, docs/howto/object-storage/s3/sse-c.md, docs/howto/object-storage/swift/tempurl.md, docs/howto/openstack/magnum/new-k8s-cluster.md, docs/reference/limitations/object-storage.md, docs/reference/versions/index.md, scripts/linkcheck.sh
With the release of linkchecker 10.3.0, `tox -e check` has started to fail on *external* links in the documentation that happen to point to a target that is being redirected. The fix included here makes linkchecker ignore, specifically, its new `http-redirected` warning.
It also does fix *some* of the links that linkchecker flags when configured *not* to ignore `http-redirected`, but it does not make sense to change all such links — for about half of them, the redirect exists for a good reason.
=> build: Fix link checks

docs/reference/versions/public.md
With the Kna1 region having been upgraded to the OpenStack Antelope release, update the version reference accordingly.
=> fix: Kna1 region is now running Antelope

docs/howto/openstack/octavia/.pages, docs/howto/openstack/octavia/metrics.md, docs/reference/features/compliant.md, docs/reference/features/public.md
* Explain how one adds a metrics endpoint in Octavia (available from OpenStack Antelope forward)
* Add the availability of that feature to the feature support matrix.
=> Explain Octavia's Prometheus endpoint

docs/howto/openstack/octavia/metrics.md, docs/reference/features/public.md
With base images for the Octavia amphorae having been updated in Kna1, `--protocol PROMETHEUS` listeners are now available in that region.
This PR will remain a Draft until the images are actually rolled out, but is good for review.
=> fix: Prometheus listeners now available in Kna1

docs/reference/features/public.md
Prometheus listeners are now available in the Fra1 region, so we update the corresponding matrix accordingly.
=> fix: Prometheus listeners now available in Fra1

scripts/linkcheck.sh
Apparently the issues causing spurious connection resets on some of our servers have been fixed, so remove those from the `linkchecker` ignore list.
Re-enable link checks for apidoc.cleura.cloud: this reverts commit 7144ce63eece81205309d0815d8d98cb9a862cb0.
Re-enable link checks for s3-kna1.citycloud.com: this reverts commit 43274d46a6610829e34b630700e76ad364e88c1e.
=> build: Re-include external Cleura links in link check

docs/reference/versions/compliant.md
The Antelope has landed in the Sto1HS region of the Compliant Cloud,
so we update the corresponding support matrix accordingly.
=> fix: Update the OpenStack Services matrix

docs/reference/features/compliant.md
Prometheus listeners are now available in the Sto1HS region of the
Compliant Cloud, so we update the corresponding matrix accordingly.
=> fix: Prometheus listeners now available in Sto1HS

docs/reference/features/public.md
Prometheus listeners are now available in the Sto2 region of the Public Cloud, so we update the corresponding matrix accordingly.
=> fix: Prometheus listeners now available in Sto2

docs/reference/features/public.md
Prometheus listeners are now available in the Dx1 region of the Public Cloud, so we update the corresponding matrix accordingly.
=> fix: Prometheus listeners now available in Dx1

docs/background/kubernetes/gardener/autoupgrades.md, docs/background/kubernetes/gardener/garden-linux.md, docs/background/kubernetes/index.md, docs/howto/kubernetes/gardener/create-shoot-cluster.md, docs/howto/kubernetes/gardener/hibernate-shoot-cluster.md, docs/howto/kubernetes/gardener/index.md, docs/howto/kubernetes/gardener/kubectl.md, mkdocs.yml
Our container orchestration engine brand, "Gardener in Cleura Cloud", may conceivably change at some point in the future. If that does happen, being able to change a single variable would facilitate the brand update.
Thus, include a new such variable, `brand_container_orchestration`, and set it to "Gardener in Cleura Cloud".
=> refactor: Introduce extra variable for container engine

docs/reference/features/compliant.md
Prometheus listeners are now available in the Sto2HS region of the Compliant Cloud, so we update the corresponding matrix accordingly.
=> fix: Prometheus listeners now available in Sto2HS

tox.ini
In version 9.5.0, the mkdocs-material project introduced a new way of interacting with the git-authors plugin. Rather than relying on that plugin to render information about page authors, mkdocs-material now does that rendering by itself:
https://github.com/squidfunk/mkdocs-material/blob/9.5.0/src/templates/partials/source-file.html#L57
In doing so, it unfortunately provides no facility to render just the author name, without their email address (a facility that *is*
available with the git-authors plugin). 
This is problematic for two reasons:
1. It might be a privacy concern, opening documentation contributors to spam from someone who scrapes the docs site for email addresses.
2. It breaks link checking, since some of the email addresses thus rendered are purposefully bogus …
=> build: Restrict mkdocs-material to 9.4.x versions

docs/.pages, docs/tutorials/index.md, mkdocs.yml, tox.ini
Add an index page to point to our tutorials on Cleura Cloud Academy.
Leave it hidden from the navigation and search for the time being.
=> feat: Add Tutorials page

docs/howto/openstack/nova/config-drive.md, docs/howto/openstack/nova/move-server-between-regions.md, docs/howto/openstack/nova/new-server.md, docs/howto/openstack/nova/new-vgpu-server.md, docs/howto/openstack/nova/rescue-server.md, docs/howto/openstack/nova/resize-server.md
Several of the how-to guides for OpenStack Nova were missing front
matter with a description field. Add that as appropriate.
=> fix: Add missing descriptions to Nova how-to guides

docs/howto/openstack/nova/new-server.md, docs/howto/openstack/nova/new-vgpu-server.md
There are issues with alt-text strings in the server creation and vGPU server creation How-To guides. We make sure alt-text strings are unique. While at it, we consistently use the imperative mood.
=> chore: Make sure there are no alt-text duplicates

docs/reference/limitations/kubernetes.md
In the Limitations subsection of the reference, update the maximum
Kubernetes version we support with Gardener (to 1.27.8).
=> fix: Update Limitations section for Gardener with Kubernetes 1.27

docs/howto/object-storage/s3/credentials.md, docs/howto/object-storage/s3/object-lock.md, docs/howto/object-storage/s3/presign.md, docs/howto/object-storage/s3/public-bucket.md, docs/howto/object-storage/s3/sse-c.md
Now that all our object storage services are listening on the regular HTTPS port (443), we no longer need to list the `:8080` suffix in our how-to guides for S3.
We still do need to keep the suffix in the how-to guides for Swift, since our `object-storage` endpoints in our service catalogs still do contain the `:8080` suffix.
=> fix: Drop :8080 port suffix from S3 how-to guides

docs/reference/features/public.md, docs/reference/versions/public.md
There are two planned decommission events:
* 2024-04-30: region Tky1
* 2024-06-30: region Dx1
=> fix: Add region decommission notes

docs/howto/openstack/keystone/.pages, docs/howto/openstack/keystone/app-creds.md
We explain what OpenStack application credentials are, and then we show how to manage them by providing specific examples. While at it, we add a new page regarding Keystone.
=> feat: Add How-To on managing application credentials

docs/reference/limitations/kubernetes.md
Update the limitations reference to reflect that Gardener in Cleura Cloud supports Kubernetes releases up to 1.28.6.
=> fix: Bump latest Gardener-installable Kubernetes release to 1.28.6

mkdocs.yml
We have a new version of the DPA, effective 2024-03-25. Update the
link, and also update the effective date and the date it was last
modified.
=> fix: Bump DPA version (and validity dates)

docs/reference/index.md
Implement the one-sentence-per line convention in the `index.md` page for the reference section.
(This was originally in PR #272, but since that hasn't moved forward in months we should probably just merge this one as-is.)
=> chore: One-sentence-per-line in index page for reference section

.github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/deploy.yml
Make sure we can build on Python 3.8 (Ubuntu Focal), Python 3.10 (Ubuntu Jammy), and Python 3.12 (latest Python release):
* Use Python 3.12 for the `check` and `deploy` GitHub Actions workflows
* Add Python 3.12 to the test matrix for the `build` workflow
* Drop Python 3.9 from the test matrix for the `build` workflow
=> build: Support Python 3.12

docs/background/kubernetes/index.md, docs/reference/limitations/kubernetes.md, scripts/linkcheck.sh
The latest Kubernetes release we can install in Magnum clusters in Cleura Cloud is 1.24, not 1.21. Update the relevant mentions in the background info and version reference pages.
=> fix: Update Magnum Kubernetes version

docs/howto/openstack/cinder/encrypted-volumes.md, docs/reference/.pages, docs/reference/index.md, docs/reference/volumes/index.md
In the reference section, add a new subsection about volume types. Explain the `cbs` and `cbs-encrypted` volume types, their encryption support, and quality-of-service (QoS) caps.
=> feat: Add reference information for volume types

docs/howto/object-storage/s3/object-lock.md
This is a follow-up from the accidentally closed PR #289.
=> Object locking update

docs/reference/volumes/index.md
The `cbs` and `cbs-encrypted` volume types only come with QoS limits in Cleura Public Cloud. Explain this fact more clearly.
=> fix: Explain that Cinder QoS limits are only enforced in Public Cloud

docs/howto/getting-started/accessing-cc-rest-api.md, docs/reference/features/public.md, docs/reference/versions/public.md
* The Dx1 region will remain available until 2024-07-21. Fix the reference information accordingly.
* The Tky1 region has been sunset. Remove all references to it.
=> fix: Extend availability for the Dx1 region, drop Tky1

docs/howto/getting-started/accessing-cc-rest-api.md, docs/reference/features/public.md, docs/reference/versions/public.md
We are now past the final deadline for customers to move out of Dx1, so we proceed with removing all relevant references from the public-facing documentation.
=> fix: Remove all references to Dx1 region

docs/reference/api/openstack/index.md
fog.io apparently no longer exists, and Fog itself lists its own project web site as fog.github.io now.
Reference:
https://github.com/fog/fog
=> fix: Update reference to Fog project page

docs/reference/limitations/openstack.md
The volume backup service is not configured in any of the Cleura Cloud regions, so we update the limitations page accordingly.
While at it, we suggest configuring servers for Disaster Recovery via the Cleura Cloud Management Panel.
=> fix: Update the limitations page to include volume backups

docs/howto/object-storage/s3/.pages, docs/howto/object-storage/s3/utilization.md, docs/howto/object-storage/swift/.pages, docs/howto/object-storage/swift/utilization.md
Explain how to retrieve the total number of objects and their cumulative size in a bucket (S3 API) or container (Swift API).
=> feat: Add how-to guides on retrieving object storage utilization

docs/reference/versions/compliant.md, docs/reference/versions/index.md, docs/reference/versions/public.md
Mention Caracal for OpenStack, and Reef for Ceph.
=> Update OpenStack and Ceph releases in version reference

docs/reference/features/public.md, docs/reference/limitations/kubernetes.md
We currently support 1.27.8 (for Caracal) with Magnum, and 1.31.5 with Gardener.
=> fix: Update supported Kubernetes releases

docs/reference/features/public.md
Object storage support in Sto2 is coming, though it's not ready for general consumption yet.
=> fix: List object storage in Sto2 as "in deployment"

docs/howto/openstack/neutron/vpnaas.md, scripts/linkcheck.sh
Excluding the VPNaaS Howto guide from .pages only means it is not
being displayed in the nagivation, but can still be found using
full-text search.
Exclude the guide from search via the search frontmatter attribute.
=> fix: Exclude VPNaaS Howto from search

docs/howto/getting-started/create-account.md, docs/reference/legal/index.md, mkdocs.yml
All legally relevant documents are now at https://cleura.com/resources/legal/terms/. Thus, for avoidance of ambiguity, refer to just that page in the Legal Reference subsection.
Also, remove the extra variables containing direct links to the PDFs, and consequently also remove references to those variables from the account creation how-to guide.
=> fix: Replace Legal page content with link to authoritative source

docs/reference/versions/compliant.md
The Sto-Com region is running OpenStack Caracal, not Antelope.
Update the version reference accordingly.
=> fix: Update OpenStack version information for Sto-Com

docs/howto/openstack/barbican/share-secret.md, docs/howto/openstack/cinder/encrypted-volumes.md, docs/reference/volumes/index.md
In relation to #239:
- chore: Apply one-sentence-per-line format to Encrypted Volumes guide
- chore: Apply one-sentence-per-line format to Sharing secrets via ACLs
- fix: Minor fixes to Sharing secrets via ACLs
- feat: Add administrative user UUIDs for encrypted volume secret sharing
=> Clarify sharing volume encryption secrets

.gitlab-ci.yml
For building from a GitLab CI/CD pipeline, deploy a separate Pages build for each topic branch.
Retain the bare Pages URL for the main branch.
References:
* https://docs.gitlab.com/ci/yaml/#pagespath_prefix
* https://docs.gitlab.com/user/project/pages/#parallel-deployments
=> build: Deploy per-branch GitLab pages

.gitlab-ci.yml
By default, GitLab Pages parallel deployments expire after just 24 hours.
That's too short for our purposes, and keeping additional deployments should be cheap, so extend the expiry period to 4 weeks.
Reference:
https://docs.gitlab.com/user/project/pages/parallel_deployments/#create-a-parallel-deployment
=> build: Keep per-branch GitLab Pages builds for 4 weeks

docs/reference/volumes/index.md
Update the volume type reference to more accurately represent the types exposed in the API.
Specifically, make sure that the separate volume types with (`-encrypted`) are represented in this table, and that the default type is not encrypted.
(Clean version of #330 which we didn't hear back on.)
=> fix: Update volume type reference

docs/howto/object-storage/s3/versioning.md
Deleting a versioned S3 bucket with lots of objects and lots of versions can become quite tedious. It's usually simpler to let the objects (and non-concurrent versions) expire, and then delete the bucket.
Add a section to the how-to to explain that.
=> feat: Add information on how to delete a versioned S3 bucket

docs/howto/object-storage/s3/versioning.md
In the S3 object versioning how-to guide, two example invocations of `s3cmd` were missing the `-c` option.
Add this option, so that the options are in line with all other `s3cmd` examples.
=> fix: Add -c option to s3cmd examples

docs/howto/openstack/magnum/kubectl.md, docs/howto/openstack/magnum/new-k8s-cluster.md
We reformat all How-Tos and index files in the magnum subcategory of the openstack category, to follow the one sentence per line policy.
=> chore: Apply the one sentence per line policy in the magnum subcategory

docs/howto/openstack/octavia/lbaas-l7pol.md, docs/howto/openstack/octavia/lbaas-tcp.md, docs/howto/openstack/octavia/metrics.md, docs/howto/openstack/octavia/tls-lb.md
We reformat all How-Tos in the octavia subcategory of the openstack category, to follow the one sentence per line policy.
=> chore: Apply the one sentence per line policy in the octavia subcategory

docs/howto/openstack/magnum/kubectl.md, docs/howto/openstack/neutron/delete-network.md, docs/howto/openstack/neutron/vpnaas.md, docs/howto/openstack/nova/boot-image-volume.md, docs/howto/openstack/nova/new-server.md, docs/howto/openstack/octavia/lbaas-l7pol.md, docs/howto/openstack/octavia/lbaas-tcp.md
There are several instances where we use the bash/plain code block combination to represent a command with its corresponding terminal output. Instead, we use the console code block.
While at it, we fix a bug where backslash characters erroneously follow the semicolon of a for-loop, and hence are visible in the rendered code block.
=> fix: Use console blocks consistently

docs/howto/object-storage/s3/credentials.md, docs/howto/object-storage/swift/public-container.md
We accurately reflect a specific endpoint schema in the S3-compatible credentials guide. We also make sure to use the correct bucket names ::in the Working with a public Swift container guide.
=> fix: Accurately reflect endpoint schema, use correct bucket names

docs/howto/object-storage/swift/tempurl.md, scripts/linkcheck.sh
The object storage infrastructure in Cleura Cloud currently exposes the Swift API without support for the SHA256 digest algorithm that is the default used by recent versions of the CLI.
Thus, in order for Swift TempURLs to work, we must specify the SHA1 digest alorithm, by using the `--digest sha1` option with the `swift tempurl` command.
This change should be reverted once all object storage servers in Cleura Cloud support SHA256 for TempURLs.
=> fix: Mention setting the digest algorithm for Swift TempURLs

docs/howto/object-storage/s3/presign.md, docs/howto/openstack/barbican/generic-secret.md, docs/howto/openstack/cinder/retype-volumes.md, docs/howto/openstack/keystone/app-creds.md, docs/howto/openstack/neutron/delete-network.md, docs/howto/openstack/nova/boot-image-volume.md, docs/howto/openstack/octavia/lbaas-tcp.md, docs/howto/openstack/octavia/tls-lb.md
* Replace a few remaining references to `fra1`, `kna1`, and `sto2` with an `api_region` variable reference. (The Neutron VPNaaS how-to is omitted; there the specific references to two distinct regions are deliberate.)
* Replace a few remaining references to `citycloud.com` with an `api_domain` variable reference.
=> fix: Replace hardcoded references to regions

docs/howto/kubernetes/index.md, docs/reference/features/compliant.md, docs/reference/limitations/openstack.md, docs/reference/volumes/index.md
Replace a few remaining references to `Sto-Com` with an `api_region` variable reference.
=> fix: Replace hardcoded references to Sto-Com

docs/reference/api/openstack/index.md, scripts/linkcheck.sh
This has been requested several times, but up to this point we had only included it in the v2 docs. Add it to main, so that it subsequently becomes available for all regions.
=> feat: Include endpoint list in API reference

scripts/run-mike.py
Rather than using Mike versions and aliases, which give us URL paths like `/kna1/` and `/Kna1/`, use just versions with a title.
This way, the URL path always contains the all-lowercase branch name (like `kna1`), whereas the drop-down has the title-cased name (like `Kna1`).
Since this means that paths that were previously symlinks now become real directories, this requires that we clean up the `gh-pages` branch with #382, before we proceed with merging this.
=> build: Use Mike version titles, not aliases

.github/workflows/deploy.yml, scripts/run-mike.py
Make Kna1 the default region.
This means that:
* Visiting https://docs.cleura.cloud/ will redirect the reader to   https://docs.cleura.cloud/kna1/ and explain that they are reading
the docs for Kna1, and need to switch to a different region if that's what they're interested in.
* Visiting any other "old", non-region-specific link (like https://docs.cleura.cloud/howto) will still work.
At a later date, we will remove the old links from the `gh-pages` branch, at which point they will become 404s.
=> feat: Fully enable Mike-based documentation

docs/howto/object-storage/swift/public-container.md, docs/howto/object-storage/swift/tempurl.md, docs/reference/api/openstack/index.md
Now that the service catalog endpoints for object-storage have been updated to drop the :8080 port suffix, we can eliminate that suffix from the how-to guides for Swift and the API reference.
=> fix: Drop :8080 port suffix from Swift how-to guides

unavailable.md
Add a Markdown file that states that the given feature is unavailable.
The purpose of this file is as follows:
* If a feature is unavailable in one Cleura Cloud region, then we can replace the Markdown file(s) in that branch with a symlink to the placeholder, and also remove the links from the navigation.
* That way, no internal links break. For example, if we have a how-to guide for a feature, and that how-to guide is replaced with the "unavailable" placeholder, then a background explainer or a cross-reference from the reference section needn't be updated.
* At the same time, we don't pollute the search index for a region with content that isn't applicable to that region.
=> feat: Add an "unavailable" placeholder

docs/reference/versions/index.md, docs/reference/versions/public.md
Fra1 is the first region we run Epoxy, so we update the documentation accordingly.
=> fix: Update documentation in light of OpenStack Epoxy

docs/howto/account-billing/.pages, docs/howto/account-billing/index.md, docs/howto/object-storage/index.md, docs/howto/openstack/.pages, docs/howto/openstack/cinder/.pages, docs/howto/openstack/cinder/index.md, docs/howto/openstack/glance/index.md, docs/howto/openstack/index.md, docs/howto/openstack/keystone/.pages, docs/howto/openstack/keystone/index.md, docs/howto/openstack/magnum/.pages, docs/howto/openstack/magnum/index.md, docs/howto/openstack/neutron/.pages, docs/howto/openstack/neutron/index.md, docs/howto/openstack/nova/.pages, docs/howto/openstack/nova/index.md, docs/howto/openstack/octavia/.pages, docs/howto/openstack/octavia/index.md, docs/howto/support/index.md
Without this change, multiple subsections in our howto section lack an index page. This is ugly and not very user-friendly, so add them.
=> feat: Add missing index pages in howto section

docs/reference/features/compliant.md, docs/reference/versions/compliant.md
With the per-region format, it no longer makes sense to restrict reference information about features and versions in Sto-Com to just that region.
Thus, add that information to the main branch.
=> fix: Add overview information for Sto-Com to all regions

docs/howto/getting-started/create-account.md, mkdocs.yml, scripts/linkcheck.sh
With per-region documentation, it makes more sense to directly use the CCMP and CCMS domain names for Compliant Cloud, in the relevant regions.
=> fix: Correct gui_domain and rest_api_domain for Compliant Cloud

docs/reference/features/public.md
Add a section adding to the feature reference (for the Public Cloud regions, for the time being).
Designate is currently in beta in Fra1.
=> feat: Add DNS to feature reference in Public Cloud

docs/howto/openstack/designate/.pages
Make sure we have the same title in the subsection navigation, and in the title of that subsection's `index.md` page.
=> fix: Align Designate navigation title with index page
