citynetwork/docs

docs/Concepts/index.md, docs/How-To_Guides/index.md, docs/Reference/index.md, docs/Tutorials/index.md, mkdocs.yml
Group the documentation into four general sections:
* Concepts
* How-to guides
* Tutorials
* Reference
This approach follows the Diátaxis model, a widely adopted technical
documentation framework.
Reference:
https://diataxis.fr/
=> feat: Add overall documentation structure

docs/You_Can_Help!/index.md
Expand the contribution guide with a paragraph containing links to style guides, quality guidelines, and other resources helpful to
technical writers.
=> feat: Add links to technical writing resources

docs/.pages, docs/reference/.pages, docs/reference/features/.pages, docs/reference/features/compliant.md, docs/reference/features/index.md, docs/reference/features/public.md, docs/reference/index.md, docs/reference/versions/.pages, docs/reference/versions/compliant.md, docs/reference/versions/index.md, docs/reference/versions/public.md, mkdocs.yml
Start the Reference section. Provide an overview of features and versions running in Cleura Cloud.
* Explain which OpenStack and Ceph releases we're running where.
* List which features are supported in which regions.
=> Add feature and version support matrix

mkdocs.yml
Changed config.extra.gui name to match the name presented in the page.
=> fix: Change gui name in config file

docs/howto/kubernetes/gardener/create-shoot-cluster.md
The Gardener how-to used very long lines. Wrap them to facilitate the review process for future changes.
=> chore: Rewrap Gardener how-to

docs/howto/object-storage/s3/versioning.md
Explain how to list the versions available for an object, how to create a versioned object, and how to remove the latest version or a specific version of an object.
Also, apply some whitespace fixes.
=> feat: Expand S3 object versioning how-to

docs/reference/features/compliant.md, docs/reference/features/public.md, docs/reference/flavors/index.md, docs/reference/index.md, mkdocs.yml
* Explain the naming convention for flavors.
* Explain the available compute tiers, and mention that not all tiers
are available in all regions.
* Add links to the feature support matrix, in order to explain how
features map to compute tiers.
=> feat: Add flavors to reference section

docs/contrib/modifications.md
Outline our expectations/suggestions for commit messages, and refer to
two helpful articles for additional background information.
=> feat: Add "A note on commit messages" to contribution guide

docs/howto/openstack/neutron/create-security-groups.md
Wrap lines, and replace tabs with spaces.
=> chore: Fix whitespace in security groups how-to guide

docs/.pages, docs/background/.pages, docs/background/gui-vs-api.md, docs/background/index.md, docs/concepts/index.md
We discuss when it is preferable to work with the Cleura Cloud Management Panel and when with the OpenStack API, e.g., via the OpenStack CLI tool.
=> feat: Add Explainer: CCMP Vs. OpenStack API

docs/howto/getting-started/.pages, docs/howto/getting-started/accessing-cc-rest-api.md
We show how to create a session token for the Cleura Cloud REST API, and then how to make sure the session works.
=> feat: Add HOWTO: Create token for the CC REST API

docs/howto/openstack/cinder/.pages, docs/howto/openstack/cinder/retype-volumes.md
Add a how-to guide for changing the type of a volume.
=> feat: Add how-to guide for retyping volumes

docs/howto/openstack/cinder/.pages, docs/howto/openstack/cinder/sync-volumes.md
Add a how-to explaining how to move data from one volume to another,
using snapshots and (optionally) retyping.
=> feat: Add how-to guide for transferring data between volumes

docs/howto/kubernetes/gardener/index.md
Delete extra word ("selecting")
=> fix: Apply minor edit (syntax)

README.md, docs/index.md, mkdocs.yml
This is a series of patches that should land in one go, when we take the site out of beta.
=> Emerge from the "beta" stage

.pymarkdown.json, docs/reference/.pages, docs/reference/features/index.md, docs/reference/index.md, docs/reference/limitations/.pages, docs/reference/limitations/index.md, docs/reference/limitations/kubernetes.md, docs/reference/limitations/object-storage.md, docs/reference/limitations/openstack.md
We need some authoritative documentation on specific features (of individual services) and their support status.
Add that to the reference section.
=> feat: Add Limitations subsection in Reference

docs/howto/object-storage/s3/.pages, docs/howto/object-storage/s3/object-lock.md, docs/reference/limitations/object-storage.md
Explain how one can use object locking in S3 to prevent data deletion or force retention periods.
=> feat: Add documentation about S3 Object Lock

mkdocs.yml
The domain is changing to cleura.cloud.
=> fix: Update servicedesk URL

docs/reference/features/compliant.md
Might have been a "feat:" PR, not sure.
=> fix: STO1HS IPv6 is being worked on

docs/howto/openstack/nova/.pages, docs/howto/openstack/nova/new-vgpu-server.md
We demonstrate how to create servers with virtual CPU support, using the OpenStack CLI utility.
=> feat: Add new HOWTO on creating vGPU servers

docs/reference/versions/public.md
The Antelope has landed on the Fra1 region, so we update the corresponding support matrix accordingly.
=> Update the OpenStack Services matrix

docs/howto/openstack/nova/new-vgpu-server.md, docs/reference/features/index.md, docs/reference/legal/index.md, docs/reference/versions/index.md, mkdocs.yml
New versions of our Terms of Service (ToS) and Data Processing Agreement (DPA) have been published on 2023-10-03.
Update the links accordingly.
=> fix: Update the ToS and DPA links

docs/background/kubernetes/index.md
Commit 339047b40338e99edfe75618b16cde05799b2e5e only fixed this in the Reference section, and missed a couple of version references in Background.
=> fix: Update supported Kubernetes releases (in Background section)

.mailmap, docs/howto/getting-started/create-account.md, docs/howto/openstack/barbican/share-secret.md, docs/howto/openstack/cinder/encrypted-volumes.md, docs/reference/volumes/index.md
Companion PR to #318, #319, and #320 for the v2 branch:
- Merge branch 'main' into v2
- feat: Add administrative user UUID for encrypted volume secret sharing
=> Merge recent changes in main to v2, add secret sharing info for Sto-Com

docs/reference/limitations/object-storage.md
Add a limitation description about lack of support for request/replay checksums and possible workarounds for popular tools.
=> Add object storage limitation on AWS checksums

docs/howto/object-storage/s3/credentials.md
Adds AWS CLI v2 configuration with internal profile support.
=> Add AWS CLI v2 configuration

docs/background/gui-vs-api.md
Reformat the "Cleura Cloud Management Panel vs. OpenStack API" to one sentence per line.
=> chore: One sentence per line for GUI vs. API page

docs/howto/getting-started/accessing-cc-rest-api.md, docs/howto/getting-started/enable-openstack-cli.md
Reformat the "getting started" How-To guides to one sentence per line.
=> One sentence per line for How-To guides in the "getting started" category

docs/howto/openstack/designate/.pages, docs/howto/openstack/designate/index.md, docs/howto/openstack/designate/recordsets.md, docs/howto/openstack/designate/zones.md, docs/reference/api/openstack/index.md, docs/reference/features/public.md
- **feat: Add DNS to feature reference in Public Cloud**
- **feat: Add new section for OpenStack Designate**
=> Fra1: Add Designate
